"""SQLite-backed idempotency and durable consumer cursors.

The existing ``messages`` table remains the source of truth.  These auxiliary
tables add two production messaging guarantees without changing legacy rows:

* a sender can reserve an idempotency key and safely retry a send; and
* a named consumer can advance a channel-scoped cursor monotonically.

All write methods use SQLite savepoints, so they are atomic in autocommit mode
and compose with a caller-owned transaction.  A caller that inserts a message
and commits an idempotency reservation should still serialize that sequence
with the same application write lock used for message inserts.
"""

from __future__ import annotations

import json
import sqlite3
import threading
import uuid
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Iterator, Mapping

from .validation import (
    DEFAULT_LIMITS,
    BridgeValidationError,
    canonical_json,
    normalize_limit,
    validate_channel,
    validate_consumer,
    validate_idempotency_key,
    validate_json_value,
    validate_non_negative_int,
    validate_reference,
    validate_sender,
    validate_sha256,
)


RELIABILITY_SCHEMA_VERSION = 1


class ReliabilityError(RuntimeError):
    """Base class for reliability-store failures safe to handle explicitly."""


class IdempotencyReservationError(ReliabilityError):
    pass


class CursorMessageNotFoundError(ReliabilityError):
    def __init__(self, channel: str, message_id: str) -> None:
        self.channel = channel
        self.message_id = message_id
        super().__init__(f"message cursor was not found in channel {channel!r}")


class IdempotencyState(str, Enum):
    PENDING = "pending"
    COMMITTED = "committed"


class ReservationStatus(str, Enum):
    RESERVED = "reserved"
    REPLAY = "replay"
    IN_PROGRESS = "in_progress"
    CONFLICT = "conflict"


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _as_utc(value: datetime) -> datetime:
    if value.tzinfo is None:
        raise ValueError("datetime must be timezone-aware")
    return value.astimezone(timezone.utc)


def _timestamp(value: datetime) -> str:
    return _as_utc(value).isoformat(timespec="microseconds").replace("+00:00", "Z")


def _parse_timestamp(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)


@contextmanager
def _savepoint(conn: sqlite3.Connection) -> Iterator[None]:
    # Generated by us, not user input, and therefore safe as a SQL identifier.
    name = f"bridge_rel_{uuid.uuid4().hex}"
    conn.execute(f"SAVEPOINT {name}")
    try:
        yield
    except BaseException:
        conn.execute(f"ROLLBACK TO SAVEPOINT {name}")
        conn.execute(f"RELEASE SAVEPOINT {name}")
        raise
    else:
        conn.execute(f"RELEASE SAVEPOINT {name}")


def ensure_reliability_schema(conn: sqlite3.Connection) -> None:
    """Create the auxiliary schema idempotently.

    A component-specific version table is used instead of ``PRAGMA
    user_version`` because the bridge database may gain independently-versioned
    components later.
    """

    with _savepoint(conn):
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS bridge_schema_components (
                component  TEXT PRIMARY KEY,
                version    INTEGER NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )
        row = conn.execute(
            "SELECT version FROM bridge_schema_components WHERE component = ?",
            ("reliability",),
        ).fetchone()
        if row is not None and int(row[0]) > RELIABILITY_SCHEMA_VERSION:
            raise ReliabilityError(
                "database reliability schema is newer than this server supports"
            )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS bridge_idempotency (
                channel          TEXT NOT NULL,
                sender           TEXT NOT NULL,
                idempotency_key  TEXT NOT NULL,
                payload_sha256   TEXT NOT NULL,
                state            TEXT NOT NULL CHECK (state IN ('pending', 'committed')),
                message_id       TEXT,
                message_seq      INTEGER,
                created_at       TEXT NOT NULL,
                expires_at       TEXT,
                PRIMARY KEY (channel, sender, idempotency_key),
                CHECK (
                    (state = 'pending' AND message_id IS NULL AND message_seq IS NULL)
                    OR
                    (state = 'committed' AND message_id IS NOT NULL AND message_seq IS NOT NULL)
                ),
                CHECK (message_seq IS NULL OR message_seq > 0),
                CHECK (length(payload_sha256) = 64)
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_bridge_idempotency_expiry "
            "ON bridge_idempotency(expires_at) WHERE expires_at IS NOT NULL"
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS bridge_consumer_cursors (
                consumer_id     TEXT NOT NULL,
                channel         TEXT NOT NULL,
                last_seq        INTEGER NOT NULL CHECK (last_seq >= 0),
                last_message_id TEXT,
                updated_at      TEXT NOT NULL,
                metadata_json   TEXT NOT NULL DEFAULT '{}',
                PRIMARY KEY (consumer_id, channel)
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_bridge_cursors_channel "
            "ON bridge_consumer_cursors(channel, last_seq)"
        )
        now = _timestamp(_utc_now())
        conn.execute(
            "INSERT INTO bridge_schema_components(component, version, updated_at) "
            "VALUES (?, ?, ?) ON CONFLICT(component) DO UPDATE SET "
            "version = excluded.version, updated_at = excluded.updated_at "
            "WHERE bridge_schema_components.version < excluded.version",
            ("reliability", RELIABILITY_SCHEMA_VERSION, now),
        )


@dataclass(frozen=True, slots=True)
class IdempotencyRecord:
    channel: str
    sender: str
    key: str
    payload_sha256: str
    state: IdempotencyState
    message_id: str | None
    message_seq: int | None
    created_at: str
    expires_at: str | None

    def is_expired(self, now: datetime | None = None) -> bool:
        return self.expires_at is not None and _parse_timestamp(self.expires_at) <= _as_utc(
            now or _utc_now()
        )


@dataclass(frozen=True, slots=True)
class ReservationResult:
    status: ReservationStatus
    record: IdempotencyRecord

    @property
    def should_insert(self) -> bool:
        return self.status is ReservationStatus.RESERVED


@dataclass(frozen=True, slots=True)
class ConsumerCursor:
    consumer_id: str
    channel: str
    last_seq: int
    last_message_id: str | None
    updated_at: str
    metadata: Mapping[str, Any]


@dataclass(frozen=True, slots=True)
class CursorAdvanceResult:
    advanced: bool
    cursor: ConsumerCursor


def _idempotency_from_row(row: sqlite3.Row | tuple[Any, ...]) -> IdempotencyRecord:
    return IdempotencyRecord(
        channel=row[0],
        sender=row[1],
        key=row[2],
        payload_sha256=row[3],
        state=IdempotencyState(row[4]),
        message_id=row[5],
        message_seq=row[6],
        created_at=row[7],
        expires_at=row[8],
    )


def _cursor_from_row(row: sqlite3.Row | tuple[Any, ...]) -> ConsumerCursor:
    try:
        metadata = json.loads(row[5])
    except (TypeError, json.JSONDecodeError):
        # Corruption should not prevent recovery/advancement; expose an empty
        # object rather than propagating JSON errors through message delivery.
        metadata = {}
    return ConsumerCursor(
        consumer_id=row[0],
        channel=row[1],
        last_seq=int(row[2]),
        last_message_id=row[3],
        updated_at=row[4],
        metadata=metadata,
    )


_IDEMPOTENCY_SELECT = (
    "SELECT channel, sender, idempotency_key, payload_sha256, state, "
    "message_id, message_seq, created_at, expires_at FROM bridge_idempotency "
)
_CURSOR_SELECT = (
    "SELECT consumer_id, channel, last_seq, last_message_id, updated_at, "
    "metadata_json FROM bridge_consumer_cursors "
)


class ReliabilityStore:
    """Repository for idempotency records and channel-scoped cursors."""

    def __init__(self, conn: sqlite3.Connection, *, initialize: bool = True) -> None:
        self.conn = conn
        self._lock = threading.RLock()
        if initialize:
            with self._lock:
                ensure_reliability_schema(conn)

    def reserve_idempotency(
        self,
        *,
        channel: str,
        sender: str,
        key: str,
        payload_sha256: str,
        ttl_seconds: int | None = 24 * 60 * 60,
        now: datetime | None = None,
    ) -> ReservationResult:
        """Atomically reserve a retry key.

        A key reused with the same digest returns ``REPLAY`` after commit or
        ``IN_PROGRESS`` while its first attempt is outstanding.  Reusing it
        with a different digest returns ``CONFLICT`` and never overwrites the
        original request.
        """

        channel = validate_channel(channel)
        sender = validate_sender(sender)
        key = validate_idempotency_key(key)
        payload_sha256 = validate_sha256(payload_sha256, field="payload_sha256")
        if ttl_seconds is not None:
            if isinstance(ttl_seconds, bool) or not isinstance(ttl_seconds, int):
                raise BridgeValidationError(
                    "ttl_seconds", "invalid_type", "must be an integer or null"
                )
            if ttl_seconds <= 0:
                raise BridgeValidationError(
                    "ttl_seconds", "out_of_range", "must be greater than zero"
                )
        instant = _as_utc(now or _utc_now())
        created_at = _timestamp(instant)
        expires_at = (
            _timestamp(instant + timedelta(seconds=ttl_seconds))
            if ttl_seconds is not None
            else None
        )

        with self._lock, _savepoint(self.conn):
            # An exact-key lazy cleanup keeps a crashed pending reservation
            # retryable without sweeping the whole table on every send.
            self.conn.execute(
                "DELETE FROM bridge_idempotency WHERE channel = ? AND sender = ? "
                "AND idempotency_key = ? AND expires_at IS NOT NULL AND expires_at <= ?",
                (channel, sender, key, created_at),
            )
            cur = self.conn.execute(
                "INSERT OR IGNORE INTO bridge_idempotency "
                "(channel, sender, idempotency_key, payload_sha256, state, "
                "message_id, message_seq, created_at, expires_at) "
                "VALUES (?, ?, ?, ?, 'pending', NULL, NULL, ?, ?)",
                (channel, sender, key, payload_sha256, created_at, expires_at),
            )
            row = self.conn.execute(
                _IDEMPOTENCY_SELECT
                + "WHERE channel = ? AND sender = ? AND idempotency_key = ?",
                (channel, sender, key),
            ).fetchone()
            if row is None:  # Defensive: INSERT/SELECT are in one savepoint.
                raise ReliabilityError("idempotency reservation disappeared")
            record = _idempotency_from_row(row)

        if cur.rowcount == 1:
            status = ReservationStatus.RESERVED
        elif record.payload_sha256 != payload_sha256:
            status = ReservationStatus.CONFLICT
        elif record.state is IdempotencyState.COMMITTED:
            status = ReservationStatus.REPLAY
        else:
            status = ReservationStatus.IN_PROGRESS
        return ReservationResult(status=status, record=record)

    def commit_idempotency(
        self,
        *,
        channel: str,
        sender: str,
        key: str,
        payload_sha256: str,
        message_id: str,
        message_seq: int,
        now: datetime | None = None,
    ) -> IdempotencyRecord:
        """Bind a pending reservation to the inserted message.

        Repeating the identical commit is safe.  Any conflicting or expired
        reservation raises :class:`IdempotencyReservationError`.
        """

        channel = validate_channel(channel)
        sender = validate_sender(sender)
        key = validate_idempotency_key(key)
        payload_sha256 = validate_sha256(payload_sha256, field="payload_sha256")
        message_id = validate_reference(message_id, "message_id")
        message_seq = validate_non_negative_int(message_seq, "message_seq")
        if message_seq == 0:
            raise BridgeValidationError(
                "message_seq", "out_of_range", "must be greater than zero"
            )
        instant = _timestamp(_as_utc(now or _utc_now()))

        with self._lock, _savepoint(self.conn):
            self.conn.execute(
                "UPDATE bridge_idempotency SET state = 'committed', message_id = ?, "
                "message_seq = ?, expires_at = NULL WHERE channel = ? AND sender = ? AND "
                "idempotency_key = ? AND payload_sha256 = ? AND state = 'pending' "
                "AND (expires_at IS NULL OR expires_at > ?)",
                (
                    message_id,
                    message_seq,
                    channel,
                    sender,
                    key,
                    payload_sha256,
                    instant,
                ),
            )
            row = self.conn.execute(
                _IDEMPOTENCY_SELECT
                + "WHERE channel = ? AND sender = ? AND idempotency_key = ?",
                (channel, sender, key),
            ).fetchone()
            if row is None:
                raise IdempotencyReservationError("idempotency reservation not found")
            record = _idempotency_from_row(row)
            if (
                record.state is not IdempotencyState.COMMITTED
                or record.payload_sha256 != payload_sha256
                or record.message_id != message_id
                or record.message_seq != message_seq
            ):
                raise IdempotencyReservationError(
                    "reservation expired, conflicts, or was committed to another message"
                )
            return record

    def release_idempotency(
        self,
        *,
        channel: str,
        sender: str,
        key: str,
        payload_sha256: str,
    ) -> bool:
        """Release only the matching *pending* reservation after a failed send."""

        channel = validate_channel(channel)
        sender = validate_sender(sender)
        key = validate_idempotency_key(key)
        payload_sha256 = validate_sha256(payload_sha256, field="payload_sha256")
        with self._lock, _savepoint(self.conn):
            cur = self.conn.execute(
                "DELETE FROM bridge_idempotency WHERE channel = ? AND sender = ? "
                "AND idempotency_key = ? AND payload_sha256 = ? AND state = 'pending'",
                (channel, sender, key, payload_sha256),
            )
            return cur.rowcount == 1

    def get_idempotency(
        self, *, channel: str, sender: str, key: str
    ) -> IdempotencyRecord | None:
        channel = validate_channel(channel)
        sender = validate_sender(sender)
        key = validate_idempotency_key(key)
        with self._lock:
            row = self.conn.execute(
                _IDEMPOTENCY_SELECT
                + "WHERE channel = ? AND sender = ? AND idempotency_key = ?",
                (channel, sender, key),
            ).fetchone()
        return _idempotency_from_row(row) if row is not None else None

    def cleanup_expired_idempotency(
        self, *, now: datetime | None = None, limit: int = 1000
    ) -> int:
        instant = _timestamp(_as_utc(now or _utc_now()))
        limit = normalize_limit(limit, default=1000, maximum=10_000)
        with self._lock, _savepoint(self.conn):
            cur = self.conn.execute(
                "DELETE FROM bridge_idempotency WHERE rowid IN ("
                "SELECT rowid FROM bridge_idempotency WHERE expires_at IS NOT NULL "
                "AND expires_at <= ? ORDER BY expires_at LIMIT ?)",
                (instant, limit),
            )
            return cur.rowcount

    def get_cursor(self, *, consumer_id: str, channel: str) -> ConsumerCursor | None:
        consumer_id = validate_consumer(consumer_id)
        channel = validate_channel(channel)
        with self._lock:
            row = self.conn.execute(
                _CURSOR_SELECT + "WHERE consumer_id = ? AND channel = ?",
                (consumer_id, channel),
            ).fetchone()
        return _cursor_from_row(row) if row is not None else None

    def advance_cursor(
        self,
        *,
        consumer_id: str,
        channel: str,
        last_seq: int,
        last_message_id: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        now: datetime | None = None,
    ) -> CursorAdvanceResult:
        """Advance a cursor monotonically; stale acknowledgements are no-ops."""

        consumer_id = validate_consumer(consumer_id)
        channel = validate_channel(channel)
        last_seq = validate_non_negative_int(last_seq, "last_seq")
        if last_message_id is not None:
            last_message_id = validate_reference(last_message_id, "last_message_id")
        if last_seq == 0 and last_message_id is not None:
            raise BridgeValidationError(
                "last_message_id",
                "inconsistent_cursor",
                "must be null when last_seq is zero",
            )
        if metadata is not None and not isinstance(metadata, Mapping):
            raise BridgeValidationError(
                "metadata", "invalid_type", "must be an object"
            )
        replace_metadata = metadata is not None
        metadata_value = dict(metadata or {})
        validate_json_value(
            metadata_value,
            field="metadata",
            max_bytes=DEFAULT_LIMITS.max_metadata_bytes,
        )
        metadata_json = canonical_json(metadata_value, field="metadata")
        updated_at = _timestamp(_as_utc(now or _utc_now()))

        with self._lock, _savepoint(self.conn):
            cur = self.conn.execute(
                "INSERT INTO bridge_consumer_cursors "
                "(consumer_id, channel, last_seq, last_message_id, updated_at, metadata_json) "
                "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(consumer_id, channel) DO UPDATE SET "
                "last_seq = excluded.last_seq, last_message_id = excluded.last_message_id, "
                "updated_at = excluded.updated_at, metadata_json = CASE WHEN ? "
                "THEN excluded.metadata_json ELSE bridge_consumer_cursors.metadata_json END "
                "WHERE excluded.last_seq > bridge_consumer_cursors.last_seq",
                (
                    consumer_id,
                    channel,
                    last_seq,
                    last_message_id,
                    updated_at,
                    metadata_json,
                    replace_metadata,
                ),
            )
            row = self.conn.execute(
                _CURSOR_SELECT + "WHERE consumer_id = ? AND channel = ?",
                (consumer_id, channel),
            ).fetchone()
            if row is None:
                raise ReliabilityError("consumer cursor disappeared")
            return CursorAdvanceResult(
                advanced=cur.rowcount == 1,
                cursor=_cursor_from_row(row),
            )

    def reset_cursor(
        self,
        *,
        consumer_id: str,
        channel: str,
        last_seq: int = 0,
        last_message_id: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        now: datetime | None = None,
    ) -> ConsumerCursor:
        """Explicitly move a cursor backwards or forwards."""

        consumer_id = validate_consumer(consumer_id)
        channel = validate_channel(channel)
        last_seq = validate_non_negative_int(last_seq, "last_seq")
        if last_message_id is not None:
            last_message_id = validate_reference(last_message_id, "last_message_id")
        if last_seq == 0 and last_message_id is not None:
            raise BridgeValidationError(
                "last_message_id",
                "inconsistent_cursor",
                "must be null when last_seq is zero",
            )
        if metadata is not None and not isinstance(metadata, Mapping):
            raise BridgeValidationError(
                "metadata", "invalid_type", "must be an object"
            )
        replace_metadata = metadata is not None
        metadata_value = dict(metadata or {})
        validate_json_value(
            metadata_value,
            field="metadata",
            max_bytes=DEFAULT_LIMITS.max_metadata_bytes,
        )
        updated_at = _timestamp(_as_utc(now or _utc_now()))
        metadata_json = canonical_json(metadata_value, field="metadata")
        with self._lock, _savepoint(self.conn):
            self.conn.execute(
                "INSERT INTO bridge_consumer_cursors "
                "(consumer_id, channel, last_seq, last_message_id, updated_at, metadata_json) "
                "VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(consumer_id, channel) DO UPDATE SET "
                "last_seq = excluded.last_seq, last_message_id = excluded.last_message_id, "
                "updated_at = excluded.updated_at, metadata_json = CASE WHEN ? "
                "THEN excluded.metadata_json ELSE bridge_consumer_cursors.metadata_json END",
                (
                    consumer_id,
                    channel,
                    last_seq,
                    last_message_id,
                    updated_at,
                    metadata_json,
                    replace_metadata,
                ),
            )
            row = self.conn.execute(
                _CURSOR_SELECT + "WHERE consumer_id = ? AND channel = ?",
                (consumer_id, channel),
            ).fetchone()
            if row is None:
                raise ReliabilityError("consumer cursor disappeared")
            return _cursor_from_row(row)

    def acknowledge_message(
        self,
        *,
        consumer_id: str,
        channel: str,
        message_id: str,
        metadata: Mapping[str, Any] | None = None,
        now: datetime | None = None,
    ) -> CursorAdvanceResult:
        """Advance to an existing message, scoped to its channel.

        This deliberately uses ``WHERE channel = ? AND id = ?``.  A message ID
        from another channel must never become a valid cursor for this one.
        """

        channel = validate_channel(channel)
        message_id = validate_reference(message_id, "message_id")
        seq = resolve_channel_message_seq(self.conn, channel, message_id)
        if seq is None:
            raise CursorMessageNotFoundError(channel, message_id)
        return self.advance_cursor(
            consumer_id=consumer_id,
            channel=channel,
            last_seq=seq,
            last_message_id=message_id,
            metadata=metadata,
            now=now,
        )

    def delete_cursor(self, *, consumer_id: str, channel: str) -> bool:
        consumer_id = validate_consumer(consumer_id)
        channel = validate_channel(channel)
        with self._lock, _savepoint(self.conn):
            cur = self.conn.execute(
                "DELETE FROM bridge_consumer_cursors WHERE consumer_id = ? AND channel = ?",
                (consumer_id, channel),
            )
            return cur.rowcount == 1


def resolve_channel_message_seq(
    conn: sqlite3.Connection, channel: str, message_id: str
) -> int | None:
    """Resolve a legacy message cursor without allowing cross-channel skips."""

    channel = validate_channel(channel)
    message_id = validate_reference(message_id, "message_id")
    row = conn.execute(
        "SELECT seq FROM messages WHERE channel = ? AND id = ?",
        (channel, message_id),
    ).fetchone()
    return int(row[0]) if row is not None else None


__all__ = [
    "ConsumerCursor",
    "CursorAdvanceResult",
    "CursorMessageNotFoundError",
    "IdempotencyRecord",
    "IdempotencyReservationError",
    "IdempotencyState",
    "RELIABILITY_SCHEMA_VERSION",
    "ReliabilityError",
    "ReliabilityStore",
    "ReservationResult",
    "ReservationStatus",
    "ensure_reliability_schema",
    "resolve_channel_message_seq",
]
